#!/usr/bin/env bash
# This script configures and starts a pre-installed InfluxDB OSS server.
# You can pass in values to be filled in the InfluxDB configuration file

set -e

# Import the appropriate bash commons libraries
readonly BASH_COMMONS_DIR="/opt/gruntwork/bash-commons"
readonly INFLUXDB_COMMONS_DIR="/opt/influxdb-commons"
readonly DEFAULT_OSS_CONFIG_FILE_PATH="/etc/influxdb/influxdb.conf"

if [[ ! -d "$BASH_COMMONS_DIR" ]]; then
  echo "ERROR: this script requires that bash-commons is installed in $BASH_COMMONS_DIR. See https://github.com/gruntwork-io/bash-commons for more info."
  exit 1
fi

if [[ ! -d "$INFLUXDB_COMMONS_DIR" ]]; then
  echo "ERROR: this script requires that influxdb-commons is installed in $INFLUXDB_COMMONS_DIR."
  exit 1
fi

source "$BASH_COMMONS_DIR/assert.sh"
source "$BASH_COMMONS_DIR/file.sh"
source "$BASH_COMMONS_DIR/log.sh"

source "$INFLUXDB_COMMONS_DIR/influxdb-common.sh"

function print_usage {
  echo
  echo "Usage: run-influxdb-oss [options]"
  echo
  echo "This script can be used to configure and initialize InfluxDB OSS. This script has been tested with Ubuntu 18.04."
  echo
  echo "Options:"
  echo

  echo -e "  --auto-fill\t\tSearch the InfluxDB config file for KEY and replace it with VALUE. May be repeated."

  echo
  echo "Example:"
  echo
  echo "  run-influxdb-oss  --auto-fill '<__CUSTOM_CONFIG_VALUE__>=******'"
}

function start_influxdb {
  set +e

  log_info "Starting InfluxDB Service"
  sudo systemctl enable influxdb.service
  sudo systemctl start influxdb.service
  echo -n "$?"

  set -e
}

function wait_for_service_to_start {
  local -r max_retries=5
  local -r sleep_between_retries=5

  for (( i=0; i<"$max_retries"; i++ )); do
    local exit_code
    exit_code=$(start_influxdb)

    if [[ "$exit_code" == "0" ]]; then
      log_info "Service started successfully."
      # The services need a few seconds to fully initialize
      sleep 5
      return
    else
      log_warn "Service couldn't start. Will sleep for $sleep_between_retries seconds and try again."
      sleep "$sleep_between_retries"
    fi
  done

  log_error "Service failed to start after $max_retries retries."
  exit 1
}

function run_influxdb {
  local -a auto_fill=()

  while [[ $# > 0 ]]; do
    local key="$1"
    case "$key" in
      --help)
        print_usage
        exit
        ;;
      --auto-fill)
        assert_not_empty "$key" "$2"
        auto_fill+=("$2")
        shift
        ;;
      *)
        echo "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  file_fill_template "$DEFAULT_OSS_CONFIG_FILE_PATH" "${auto_fill[@]}"

  wait_for_service_to_start
}

run_influxdb "$@"
